apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nest-api
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: nest-api
  namespaceSelector:
    matchNames:
      - nest-api-main
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
